name = "StableHashTraits"
uuid = "c5dd0088-6c3f-4803-b00e-f31a60c170fa"
authors = ["Beacon Biosignals, Inc."]
version = "0.3.1"

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
Compat = "3, 4"
Tables = "1.7"
TupleTools = "1"
julia = "1.6"
