name = "StableHashTraits"
uuid = "c5dd0088-6c3f-4803-b00e-f31a60c170fa"
authors = ["Beacon Biosignals, Inc."]
version = "1.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
PikaParser = "3bbf5609-3e7b-44cd-8549-7c69f321e792"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
AWSS3 = "0.10"
Aqua = "0.8"
BenchmarkTools = "1"
CRC32c = "1"
Compat = "3, 4"
DataFrames = "1.4"
Dates = "1"
PikaParser = "0.6"
Pluto = "0.19"
ReferenceTests = "0.10"
SHA = "0.7, 1"
StructTypes = "1"
Tables = "1.7"
Test = "1"
TupleTools = "1"
UUIDs = "1"
julia = "1.6"

[extras]
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[targets]
test = ["AWSS3", "Aqua", "BenchmarkTools", "CRC32c", "DataFrames", "Dates", "Pluto", "ReferenceTests", "Test", "UUIDs"]
